-- AlterTable
ALTER TABLE "tenants" ADD COLUMN     "deviceLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "dueDate" TIMESTAMP(3),
ADD COLUMN     "monthlyFee" DOUBLE PRECISION NOT NULL DEFAULT 50000;
